execute pathogen#infect()

filetype on
filetype indent on
syntax on
colorscheme neon


"set lines=35 columns=150
"set colorcolumn=120
set nowrap
set number
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set autoindent
set showmatch

let mapleader=" "

map <leader>s :source ~/.vimrc<CR>
map <D-A-RIGHT> <C-w>l
map <D-A-LEFT> <C-w>h
map <D-A-DOWN> <C-w><C-w>
map <D-A-UP> <C-w>W

let NERDTreeMapActivateNode='<right>'
let NERDTreeShowHidden=1

nmap <leader>n :NERDTreeToggle<CR>
nmap <leader>j :NERDTreeFind<CR>

autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd p

let NERDTreeIgnore=['\.DS_Store', '\~$', '\.swp']
