[tools]
"cargo:bob-nvim" = "latest"
go = "latest"
gradle = "8.10.1"
java = "temurin-21"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@bufbuild/buf" = "latest"
"npm:@github/copilot" = "latest"
rust = "latest"
terraform = "1.13.2"
tflint = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "java"]
