return {
  {
    "folke/snacks.nvim",
    opts = {
      picker = {
        win = {
          input = {
            keys = {
              ["/"] = "toggle_focus",
              ["<C-Down>"] = { "history_forward", mode = { "i", "n" } },
              ["<C-Up>"] = { "history_back", mode = { "i", "n" } },
              ["<C-w>"] = { "<c-s-w>", mode = { "i" }, expr = true, desc = "delete word" },
              ["<CR>"] = { "confirm", mode = { "n", "i" } },
              ["<Down>"] = { "list_down", mode = { "i", "n" } },
              ["<Esc>"] = "cancel",
              ["<Up>"] = { "list_up", mode = { "i", "n" } },
              ["<c-h>"] = { "toggle_hidden", mode = { "i", "n" } },
              ["<c-i>"] = { "toggle_ignored", mode = { "i", "n" } },
              ["<c-m>"] = { "toggle_maximize", mode = { "i", "n" } },
              ["<c-p>"] = { "toggle_preview", mode = { "i", "n" } },
              ["<c-s>"] = { "edit_split", mode = { "i", "n" } },
              ["<c-t>"] = { "tab", mode = { "n", "i" } },
              ["<c-v>"] = { "edit_vsplit", mode = { "i", "n" } },
              ["<c-w>H"] = "layout_left",
              ["<c-w>J"] = "layout_bottom",
              ["<c-w>K"] = "layout_top",
              ["<c-w>L"] = "layout_right",
              ["?"] = "toggle_help_input",
              ["G"] = "list_bottom",
              ["gg"] = "list_top",
              ["q"] = "close",
              ["<c-c>1"] = { "cancel", mode = "i" },
              ["<c-c>2"] = { { "pick_win", "jump" }, mode = { "n", "i" } },
              ["<c-c>3"] = { "select_and_prev", mode = { "i", "n" } },
              ["<c-c>4"] = { "select_and_next", mode = { "i", "n" } },
              ["<c-c>5"] = { "inspect", mode = { "n", "i" } },
              ["<c-c>6"] = { "toggle_follow", mode = { "i", "n" } },
              ["<c-c>7"] = { "cycle_win", mode = { "i", "n" } },
              ["<c-c>8"] = { "select_all", mode = { "n", "i" } },
              ["<c-c>9"] = { "preview_scroll_up", mode = { "i", "n" } },
              ["<c-c>10"] = { "list_scroll_down", mode = { "i", "n" } },
              ["<c-c>11"] = { "preview_scroll_down", mode = { "i", "n" } },
              ["<c-c>12"] = { "toggle_live", mode = { "i", "n" } },
              ["<c-c>13"] = { "list_down", mode = { "i", "n" } },
              ["<c-c>14"] = { "list_up", mode = { "i", "n" } },
              ["<c-c>15"] = { "list_down", mode = { "i", "n" } },
              ["<c-c>16"] = { "list_up", mode = { "i", "n" } },
              ["<c-c>17"] = { "qflist", mode = { "i", "n" } },
              ["<c-c>18"] = { "list_scroll_up", mode = { "i", "n" } },
              ["<c-c>19"] = { "insert_alt", mode = "i" },
              ["<c-c>20"] = { "insert_filename", mode = "i" },
              ["<c-c>21"] = { "insert_cWORD", mode = "i" },
              ["<c-c>22"] = { "insert_file", mode = "i" },
              ["<c-c>23"] = { "insert_line", mode = "i" },
              ["<c-c>24"] = { "insert_file_full", mode = "i" },
              ["<c-c>25"] = { "insert_cword", mode = "i" },
              ["<c-c>26"] = "list_down",
              ["<c-c>27"] = "list_up",
            },
          },
        },
      },
    },
  },
}
