-- local M = {}
--
-- wezterm.on("format-tab-title", function(tab, tabs, _, _, hover, _)
-- 	local background = NEW_TAB_BG
-- 	local foreground = NEW_TAB_FG
--
-- 	local is_first = tab.tab_id == tabs[1].tab_id
--
-- 	if tab.is_active then
-- 		background = ACTIVE_TAB_BG
-- 		foreground = ACTIVE_TAB_FG
-- 	elseif hover then
-- 		background = HOVER_TAB_BG
-- 		foreground = HOVER_TAB_FG
-- 	end
--
-- 	local leading_bg = background
-- 	local trailing_fg = background
--
-- 	local function check_start_arrow()
-- 		return " "
-- 	end
--
-- 	local title = get_window_title(tab)
-- 	if is_first then
-- 		title = title .. " "
-- 	else
-- 		title = " " .. title .. " "
-- 	end
--
-- 	return {
-- 		{
-- 			Background = {
-- 				Color = leading_bg,
-- 			},
-- 		},
-- 		{
-- 			Foreground = {
-- 				Color = TAB_BAR_BG,
-- 			},
-- 		},
-- 		{
-- 			Text = check_start_arrow(),
-- 		},
-- 		{
-- 			Attribute = {
-- 				Intensity = "Half",
-- 			},
-- 		},
-- 		,{
-- 			Background = {
-- 				Color = background,
-- 			},
-- 		},
-- 		{
-- 			Foreground = {
-- 				Color = foreground,
-- 			},
-- 		}, -- { Text = string.format(" %s", tab.tab_index + 1) },
-- 		{
-- 			Attribute = {
-- 				Intensity = "Normal",
-- 			},
-- 		},
-- 		{
-- 			Background = {
-- 				Color = background,
-- 			},
-- 		},
-- 		{
-- 			Foreground = {
-- 				Color = foreground,
-- 			},
-- 		},
-- 		{
-- 			Text = string.format("%s", title),
-- 		},
-- 		{
-- 			Background = {
-- 				Color = TAB_BAR_BG,
-- 			},
-- 		},
-- 		{
-- 			Foreground = {
-- 				Color = trailing_fg,
-- 			},
-- 		},
-- 		-- {
-- 		-- 	Text = SOLID_RIGHT_ARROW,
-- 		-- },
-- 	}
-- end)
--
