#!/usr/bin/env zsh

function renew_tokens() {
  toolbelt credentials.generate -u $1 -a $2 && toolbelt codeartifact.token && export AWS_PROFILE=terraform
}

function pwcopy() {
  LC_CTYPE=C \
    tr </dev/urandom \
    \
    -dc a-zA-Z0-9 |
    head -c ${1:-16} |
    pbcopy &&
    pbpaste &&
    echo
}

function docker_images_prune() {
  docker stop $(docker ps -a -q)
  docker system prune --all --force
}

function docker_container_prune() {
  docker stop $(docker ps -a -q)
  docker container prune --force
}

function kafka_start() {
  confluent local services start
  if [ $? -eq 0 ]; then
    echo Kafka on localhost:9092
    echo Zookeeper on localhost:2181
    echo Schema registry on localhost:8081
    echo Control Center UI on http://localhost:9021
  else
    confluent local current | xargs rm -rf
  fi
}

function kafka_stop() {
  confluent local services stop
  if [ $? -eq 0 ]; then
    confluent local current | xargs rm -rf
  fi
}

function db() {
  export AWS_PROFILE=terraform
  echo "$AWS_PROFILE"
  i=1
  services=()
  if [ -z "$1" ]; then
    while IFS= read -r line; do
      services+=("$line")
    done < <(toolbelt database.list -p $AWS_PROFILE)
  else
    while IFS= read -r line; do
      services+=("$line")
    done < <(toolbelt database.list -p $AWS_PROFILE | grep $1)
  fi
  for service in "${services[@]}"; do
    echo "[$i] $service"
    ((i++))
  done
  echo "Select DB"
  read selected
  selected_db="${services[$selected]}"
  echo "toolbelt database.connection $selected_db"
  toolbelt database.connection $selected_db -p $AWS_PROFILE
}

docker_run() {
  open -a Docker
}

function delete_old_branch() {
  git fetch -p && git branch -vv | awk '/: gone]/{print $1}' | xargs git branch -D
  #  git fetch -p && for branch in $(git for-each-ref --format '%(refname) %(upstream:track)' refs/heads | awk '$2 == "[gone]" {sub("refs/heads/", "", $1); print $1}'); do git branch -D $branch; done
}

function gpg-no-tty() {
  echo passphrase | gpg --passphrase-fd 0 --batch --no-tty --yes "$@"
}

function datagrip() {
  #!/bin/bash
  #Generated by JetBrains Toolbox 1.22.10970 at 2022-02-24T12:20:37.786528

  declare -a ideargs=()
  declare -- wait=""

  for o in "$@"; do
    if [[ "$o" = "--wait" || "$o" = "-w" ]]; then
      wait="-W"
      o="--wait"
    fi
    if [[ "$o" =~ " " ]]; then
      ideargs+=("\"$o\"")
    else
      ideargs+=("$o")
    fi
  done

  open -na "/Users/aheggert/Library/Application Support/JetBrains/Toolbox/apps/datagrip/ch-0/213.6777.22/DataGrip.app/Contents/MacOS/datagrip" $wait --args "${ideargs[@]}"
}

function idea() {
  #!/bin/bash
  #Generated by JetBrains Toolbox 1.22.10970 at 2022-02-24T12:20:37.776510

  declare -a ideargs=()
  declare -- wait=""

  for o in "$@"; do
    if [[ "$o" = "--wait" || "$o" = "-w" ]]; then
      wait="-W"
      o="--wait"
    fi
    if [[ "$o" =~ " " ]]; then
      ideargs+=("\"$o\"")
    else
      ideargs+=("$o")
    fi
  done

  open -na "/Users/aheggert/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.6777.52/IntelliJ IDEA.app/Contents/MacOS/idea" $wait --args "${ideargs[@]}"
}

function studio() {
  #!/bin/bash
  #Generated by JetBrains Toolbox 1.22.10970 at 2022-02-24T12:20:37.782722

  declare -a ideargs=()
  declare -- wait=""

  for o in "$@"; do
    if [[ "$o" = "--wait" || "$o" = "-w" ]]; then
      wait="-W"
      o="--wait"
    fi
    if [[ "$o" =~ " " ]]; then
      ideargs+=("\"$o\"")
    else
      ideargs+=("$o")
    fi
  done

  open -na "/Users/aheggert/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401/Android Studio.app/Contents/MacOS/studio" $wait --args "${ideargs[@]}"
}
