#!/bin/bash
wget --limit-rate=200k --no-clobber --convert-links --random-wait -r -p -E -e robots=off $1
#wget \
#     --recursive \
#     --no-clobber \
#     --page-requisites \
#     --html-extension \
#     --convert-links \
#     --restrict-file-names=windows \
#     --domains website.org \
#     --no-parent \
 #    $1	
