[general]
import = ["~/.config/alacritty/themes/dracula.toml"]

[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"
