#!/usr/bin/env bash

export PATH=$PATH:$WORKSPACE/dotfiles/bash/executables/
#EXPORT
#if [[ "$HOSTNAME" == 'deathstar' ]]; then
  #HOME PC
 # export WORKSPACE=/c/Users/oparo/Documents/Workspace
#else
  #WORK PC
  export WORKSPACE=$HOMEPATH/Documents/workspace
#fi


source $WORKSPACE/dotfiles/bash/lib/helper.bash
_load_bash_files $WORKSPACE/dotfiles/bash/plugins/
_load_bash_files $WORKSPACE/dotfiles/bash/aliases/
_load_bash_files $WORKSPACE/dotfiles/bash/themes/
# _load_bash_files $WORKSPACE/dotfiles/bash/completion/
