#!/usr/bin/env bash

#EXPORT
if [[ "$HOSTNAME" == 'deathstar' ]]; then
  #HOME PC
  export WORKSPACE=/c/Users/ArthurH/Documents/Workspace
else
  #WORK PC
  export WORKSPACE=/c/Users/aheggert/Documents/workspace
fi

source $WORKSPACE/dotfiles/bash/lib/helper.bash
_load_bash_files $WORKSPACE/dotfiles/bash/plugins/
_load_bash_files $WORKSPACE/dotfiles/bash/aliases/
# _load_bash_files $WORKSPACE/dotfiles/bash/completion/
