alias open_tasy='javaws ~/Desktop/tasy-acesso-interno.jnlp'
alias run_ecm='cd ~/Documents/Workspace/ecm-frontend/ && npm start'
alias run_cockpit='cd ~/Documents/Workspace/cockpit-frontend/ && npm start'
alias run_simple='cd ~/Documents/Workspace/simplified_process_editor/ && npm start'
alias run_modelador='cd ~/Documents/Workspace/modelador-frontend/ && npm run build:dev && npm start'