"$schema" = 'https://starship.rs/config-schema.json'

# https://github.com/VictorPLopes/OneDark-Pro-Starship?tab=readme-ov-file
# Configures the format of the prompt.
format = """
[╭╴](fg:arrow)$username\
$hostname\
[󰅂 ](fg:syntax_fg)\
$directory\
[](fg:syntax_fg)\
$git_branch\
$git_status\

$rust\
$golang\
$nodejs\
$java\
$kotlin\
$python\
$gradle\
$docker_context\

$fill\
([ ](mono4)\
$os\
$time\
$battery\
[ ](mono4))\
$line_break[╰─](fg:mono1)$character"""

# Sets the palette to "one_dark".
palette = 'one_dark'

# Sets the colors of the "one_dark" palette.
[palettes.one_dark]
mono0 = '#d7dae0'         # terminal white, from the One Dark Pro VSCode theme.
mono1 = '#abb2bf'         # syntax_fg.
mono2 = '#828997'
mono3 = '#5c6370'
mono4 = '#3f4451'         # terminal black, from the One Dark Pro VSCode theme.
color_red0 = '#e06c75'
color_red1 = '#be5046'
color_green = '#98c379'
color_yellow = '#e5c07b'
color_blue = '#61afef'
color_purple = '#c678dd'
color_cyan = '#56b6c2'
color_orange = '#d19a66'
syntax_fg = '#abb2bf'
syntax_bg = '#282c34'
color_bg2 = '#665c54'
syntax_gutter = '#647382'
syntax_accent = '#528cff'

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

# Module that displays the current OS.
[os]
disabled = true                # Disabled by default
style = "bg:mono4 fg:mono1"
format = '[ $symbol ]($style)'

# Sets custom symbols for each OS.
[os.symbols]
Alpine = ""
Amazon = ""
Android = "󰀲"
Arch = ""
CentOS = ""
Debian = "󰣚"
EndeavourOS = ""
Fedora = "󰣛"
FreeBSD = "󰣠"
Gentoo = "󰣨"
Illumos = ""
Linux = "󰌽"
Macos = "󰀵"
Manjaro = "󱘊"
Mint = "󰣭"
NixOS = "󱄅"
OpenBSD = ""
openSUSE = ""
Pop = ""
Raspbian = ""
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Redox = "R"
Solus = ""
SUSE = ""
Ubuntu = "󰕈"
Unknown = ""
Windows = "󰍲"

# Module that displays the current username.
[username]
show_always = true
style_user = "bold fg:mono3"
style_root = "bold fg:mono3"
format = '[ $user ]($style)'

[hostname]
format = '[@ $hostname](fg:$style)'
disabled = false
ssh_only = true

# Module that displays the current directory.
[directory]
style = "bold fg:color_orange"
#format = "[ $path ]($style)"
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 3
truncation_symbol = "…/"
read_only_style = "fg:color_red1"
before_repo_root_style = "fg:color_red1"
truncate_to_repo = true
read_only = "  "


# Sets the custom symbols for directories.
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

# Module that displays the current git branch.
[git_branch]
symbol = " "
style = "fg:color_cyan"
format = '[[ $symbol$branch ](fg:color_cyan)]($style)'

# Module that displays the current git status.
[git_status]
style = "fg:color_cyan"
modified = '!$count'
renamed = '»$count'
deleted = '✘$count'
ahead = '⇡$count'
behind = '⇣$count'
diverged = '⇕$count'
format = '[($all_status$ahead_behind)]($style)'

# Language specific modules
[nodejs]
symbol = ""
style = "fg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[c]
symbol = ""
style = "fg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[dotnet]
symbol = "󰪮"
style = "fg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[rust]
symbol = ""
style = "fg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[golang]
symbol = ""
style = "fg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[php]
symbol = ""
style = "fg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[java]
symbol = ""
style = "fg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "fg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[haskell]
symbol = ""
style = "fg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[python]
symbol = ""
style = "fg:color_blue"
format = '[[ $symbol($version)(\($virtualenv\)) ](fg:color_blue)]($style)'

[elixir]
symbol = ""
style = "fg:color_blue"
format = '[[ $symbol ($version) ](fg:color_blue)]($style)'

[elm]
symbol = ""
style = "fg:color_blue"
format = '[[ $symbol ($version) ](fg:color_blue)]($style)'

[gradle]
symbol = ""
style = "fg:color_blue"
format = '[[ $symbol ($version) ](fg:color_blue)]($style)'

[julia]
symbol = ""
style = "fg:color_blue"
format = '[[ $symbol ($version) ](fg:color_blue)]($style)'

[nim]
symbol = "󰆥"
style = "fg:color_blue"
format = '[[ $symbol ($version) ](fg:color_blue)]($style)'

[scala]
symbol = ""
style = "fg:color_blue"
format = '[[ $symbol ($version) ](fg:color_blue)]($style)'

# Module that displays the docker context.
[docker_context]
symbol = ""
style = "fg:mono3"
format = '[[ $symbol( $context) ](fg:mono3)]($style)'

# Module that fills the space between the left and right segments.
[fill]
symbol = " "

# Module that displays the time.
[time]
disabled = false                                    # Disabled by default
use_12hr = false                                    # Disable for 24h format without seconds
style = "bg:mono4"
format = '[[$time](fg:syntax_fg bg:mono4)]($style)'

# Module that displays the battery level and status.
[battery]
disabled = true
format = '[$symbol $percentage ]($style)'

# Battery symbols and colors for each threshold.
[[battery.display]]
threshold = 10
style = "bold bg:mono4 fg:color_red1"
discharging_symbol = "󰁺"
charging_symbol = "󰢜"

[[battery.display]]
threshold = 20
style = "bold bg:mono4 fg:color_red0"
discharging_symbol = "󰁻"
charging_symbol = "󰂆"

[[battery.display]]
threshold = 30
style = "bold bg:mono4 fg:color_yellow"
discharging_symbol = "󰁼"
charging_symbol = "󰂇"

[[battery.display]]
threshold = 40
style = "bold bg:mono4 fg:color_yellow"
discharging_symbol = "󰁽"
charging_symbol = "󰂈"

[[battery.display]]
threshold = 50
style = "bold bg:mono4 fg:color_yellow"
discharging_symbol = "󰁾"
charging_symbol = "󰢝"

[[battery.display]]
threshold = 60
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "󰁿"
charging_symbol = "󰂉"

[[battery.display]]
threshold = 70
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "󰂀"
charging_symbol = "󰢞"

[[battery.display]]
threshold = 80
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "󰂁"
charging_symbol = "󰂊"

[[battery.display]]
threshold = 90
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "󰂂"
charging_symbol = "󰂋"

[[battery.display]]
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "󰁹"
charging_symbol = "󰂅"
threshold = 100

# New line character
[character]
success_symbol = '[󰅂](bold fg:color_green)'
error_symbol = '[](bold fg:color_red1)'
vimcmd_symbol = '[󰅁](bold fg:syntax_accent)'
vimcmd_replace_one_symbol = '[󰅁](bold fg:color_purple)'
vimcmd_replace_symbol = '[󰅁](bold fg:color_purple)'
vimcmd_visual_symbol = '[󰅁](bold fg:color_yellow)'
